### ISSUE TITLE
Can't request crafting while not in the crafting station gui

### ISSUE THREAD

**Issue by sp-guip** [McJty/RFToolsControl#11]
http://imgur.com/a/YDjqe
https://bpaste.net/show/d30063bc1343

**Comment by McJty** [comment]
Sorry I don't understand this. What is the problem?

**Comment by sp-guip** [comment]
when you leave the gui it completely stops the operation untill you open it back

**Comment by sp-guip** [comment]
it only heppens on a multi step process

**Comment by McJty** [comment]
Well that's simply not possible and I don't see how your screenshots demonstrate that

**Comment by sp-guip** [comment]
there is a one from a minute after I closed the gui and no progress was done

**Comment by McJty** [comment]
That means something else was wrong. Perhaps a problem in the processor or program running on that processor or so. Because it really is technically impossible that opening the gui has an effect on this operation since it is a totally different machine that is doing this and the processor has no idea that there is a gui open for another machine

**Comment by sp-guip** [comment]
heppened in the exect same implemention you did on your video.
and I checked it out it has no problam except requesting a substance required to the crafting

**Comment by McJty** [comment]
Note that what *can* happen is that you see the requests being cleaned up from the list because that happens client side and only when the gui is open. But that has no effect on the crafting since that's done in the other machine.

So it is possible that you return after several minutes and then see the messages 'craft ok/failed' appear. But that's for things that were done some time ago already

**Comment by sp-guip** [comment]
no cause it didn't make progress at all you see that after a minute it's 20 to go but after 5 second it goes to 19... http://imgur.com/rnHWTwu

**Comment by McJty** [comment]
Oh, perhaps you *are* right. Just found a really strange bug with that cleaning up.

Sorry for doubting you. Seems there is a weird interaction going on then

**Comment by sp-guip** [comment]
That's all good I was just really annoyed by the fact I couldn't really use your awesome crafting system whilst not babysiting it...

**Comment by McJty** [comment]
Fixed now. I will release tomorrow

**Comment by sp-guip** [comment]
thanks that was quick.
