### ISSUE TITLE
Crash using crafting bench 1.12.2 latest version.

### ISSUE THREAD

**Issue by Slowwloriss** [McJty/RFToolsControl#113]
Hello. I crafted the workebench for test ( that crafted with crafting table, machine frame and chest) and when i try to craft something.. the game crash.. this is the crashlog with latest forge version:

[https://pastebin.com/N34VY7k2](https://pastebin.com/N34VY7k2)

**Comment by McJty** [comment]
Correct link:

https://pastebin.com/N34VY7k2

But I'll check it out

**Comment by xannor** [comment]
I was just playing with and learning the autocrafting for controls (I really like the idea of using rf tools/xnet/and controls as an alternative to AE/RS) and I got the same error. I tried testing a few things and it seems to occur when trying to take from the results. I even created the card by hand instead of JEI to see if that was causing the issue. I then tried just using the bench, just had to put one oak plan in the center and attempt to fetch the button in the results and crash. Interestingly using controls the craft fails with an error but no client or server crash. No error logged on the server side either.

**Comment by Slowwloriss** [comment]
YEah, was when i tried to retrieve the result of crafting, but with planks, wheat, everything

**Comment by McJty** [comment]
RFTools Control is next on my todo now so I will look at this soon

**Comment by 666lumberjack** [comment]
I have a similar crash, but it happens as soon as I release my mouse after placing anything in the Workbench's crafting grid. My log: https://paste.ee/p/TIEcA

**Comment by McJty** [comment]
This is already fixed in latest version
