### ISSUE TITLE
Fluid duplication bug with Processor/Multi Tank/AE Fluid Interface setup

### ISSUE THREAD

**Issue by novemix** [McJty/RFToolsControl#148]
Enigmatica 2: Expert (non skyblock) pack version 1.58 (from Twitch).   Is a 3 block high setup, with multi tank on bottom, then Processor on top of that, then AE Fluid Interface (in block form) on top of that.

In trying to work around #147 , (can't drop a bucket to specify fluid), I populated a variable with the fluid name using examine liquid (specifying a slot in the AE Fluid Interface) and set variable.

Then, if I call fetch liquid (set to 1mb), it takes 1mb from AE, and populates the internal tank with 1mb.
Call fetch liquid again, it takes 1mb from AE, but adds 2mb to internal, totaling 3mb.
Call fetch liquid again, it takes 1mb from AE, but adds 4mb to internal, totaling 7mb.
I think you see the pattern, I think 14mb can become 16383 mb after several calls.

I ran into this because I was trying to transfer 10 000 mb of a fluid, but the AE Fluid Interface only stocks 4000, so two calls of fetching 4000 resulted not in 8000, but 12000 mb.

**Comment by Acru** [comment]
I ran into this issue and had a look.

@McJty
It looks like the bug is on line [1754 of ProcessorTileEntity.java](https://github.com/McJtyMods/RFToolsControl/blob/8d43bb967b71c71cb6b57361691ee2da0e5a9270/src/main/java/mcjty/rftoolscontrol/blocks/processor/ProcessorTileEntity.java#L1754) where the existing fluid in the tank is added to the amount before filling the tank, duplicating the tank's contents.

This seems to have occurred in [this commit](https://github.com/McJtyMods/RFToolsControl/commit/bf370ede7667fce3820dbcf863fc5927f6629bb2) when the set was changed to a fill, but the above code was not also edited to reflect the change.

I wonder how many people encountered this bug in the last 5 years, heh.

**Comment by Acru** [comment]
I notice the bug was replicated all the way into the 1.16 version too, [line 1734](https://github.com/McJtyMods/RFToolsControl/blob/eabdb993e2dbf054b311aeab6e548faf7134feb4/src/main/java/mcjty/rftoolscontrol/modules/processor/blocks/ProcessorTileEntity.java#L1734)

**Comment by Primitive-Human** [comment]
Nothing seems to have been done to fix this to date. I'd have to rethink my fluid autocrafting thoroughly in order to get around this stupid fluid dupe.

**Comment by McJty** [comment]
Sorry, forgot about this. I'll check it out

**Comment by McJty** [comment]
Fixing this right now. This evening I can release a fix

**Comment by McJty** [comment]
Fixed next release (soon)
