### ISSUE TITLE
Fetch items deleting variable info

### ISSUE THREAD

**Issue by toddythebody** [McJty/RFToolsControl#85]
The fetch items opcode is deleting variable data. I've used the log opcode before and after the fetch items opcode to find where the data was being deleted. I've been using a read token to store variable as a work around to remind what data is supposed to be stored in the variable.

The program is supposed to fetch all of one item put of an inventory, but because it was forgetting the data stored in the variable, it was grabbing all items of all types. So now I'm storing data to a token and rereading the token and storing data every loop.

Also the fetch items opcode didn't care what was stored on the token. That's why I'm storing data from the token to a variable.

**Comment by McJty** [comment]
I need to see the program that does that

**Comment by toddythebody** [comment]
This is the one that deletes the variable.

https://pastebin.com/KdKhBJHn

This is my work around.

https://pastebin.com/y0rc8p71

The inventory I'm pulling from is the side of a player interface, and the inventory I'm pushing to is a storage scanner module.

**Comment by McJty** [comment]
The code of Fetch Items doesn't do anything with variables so that would be really strange. But I'll check it out

**Comment by McJty** [comment]
But I have a clue what is going on

**Comment by McJty** [comment]
The problem is that the 'examine item' opcode doesn't make a copy of the item. So what happens is that the item directly from the inventory is stored in the variable. As soon as you extract that item it is made empty which will also clear the variable as it is refering to the same. I need to make a copy in 'examine item' to avoid this problem. I will do that for next release. Thanks for pointing this out.
